apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixelscan-deployment
spec:
  selector:
    matchLabels:
      app: pixelscan
  template:
    metadata:
      labels:
        app: pixelscan
    spec:
      containers:
      - name: pixelscan
        image: disgruntledjarl/pixel-scan:2.3
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "250m"
            memory: "150Mi"
          limits:
            cpu: "500m"
            memory: "300Mi"
