apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixelscan-deployment
spec:
  selector:
    matchLabels:
      app: pixelscan
  template:
    metadata:
      labels:
        app: pixelscan
    spec:
      containers:
      - name: pixelscan

        # Image is already uploaded to public registry
        image: disgruntledjarl/pixel-scan:3 
        ports:
        - containerPort: 5000

        # Resource definition is based on Load testing
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
