apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pixelscan-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pixelscan-deployment
  minReplicas: 1
  maxReplicas: 14
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30  # Wait for 15 seconds before acting on scale-down
      policies:
      - type: Pods
        value: 1                      # Reduce 1 pod at most per 5 seconds
        periodSeconds: 15
