apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pixelscan-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pixelscan-deployment
  minReplicas: 1
  
  # 3 pods can be put on a node as per load testing and node metrics
  # Cluster autoscaling allows for 2 nodes, hence total of 6 pods
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  behavior:
    scaleDown:
      
      # Wait for 30 seconds before acting on scale-down
      stabilizationWindowSeconds: 30  
     
      # Reduce 1 pod at most per 5 seconds
      policies:
      - type: Pods
        value: 1                      
        periodSeconds: 15
